# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapToolKitDialog
                                 A QGIS plugin
 lesteryan map tool kit
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-26
        git sha              : $Format:%H$
        copyright            : (C) 2023 by lesteryan
        email                : cgmsyx@163.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt
from .mtk_widget_base import Ui_MapToolKitWidgetBase


class MapToolKitWidget(QtWidgets.QWidget, Ui_MapToolKitWidgetBase):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)